### PR TITLE
Minor smells fixed

### LINKED ISSUE #16: Minor smells
There are few minor smells  in the code: e.g.: nested if statements, parameter re-assignation, fields declared near the bottom of the class

### PR DESCRIPTION
**Pull request by dim5**
Fixes #16

### CODE REVIEW

File: app/src/main/java/app/outlay/view/activity/SingleFragmentActivity.java [hunk 1]
```diff
@@ -10,6 +10,8 @@
 
 public class SingleFragmentActivity extends ParentActivity {
 
+    public final static String FRAGMENT_PARAM = "fragment";
```
Comment (barni9606) [inline app/src/main/java/app/outlay/view/activity/SingleFragmentActivity.java]: moved up

File: app/src/main/java/app/outlay/view/numpad/NumpadView.java [hunk 2]
```diff
@@ -180,4 +171,14 @@ private void updateAttachedView(String str, boolean useValidator) {
             attachedEditable.setText(str);
         }
     }
+
```
Comment (barni9606) [inline app/src/main/java/app/outlay/view/numpad/NumpadView.java]: moved down

File: app/src/main/java/app/outlay/view/helper/itemtouch/SimpleItemTouchHelperCallback.java [hunk 3]
```diff
@@ -80,12 +80,10 @@ public void onChildDraw(Canvas c, RecyclerView recyclerView, RecyclerView.ViewHo
     @Override
     public void onSelectedChanged(RecyclerView.ViewHolder viewHolder, int actionState) {
         // We only want the active item to change
-        if (actionState != ItemTouchHelper.ACTION_STATE_IDLE) {
-            if (viewHolder instanceof ItemTouchHelperViewHolder) {
-                // Let the view holder know that this item is being moved or dragged
-                ItemTouchHelperViewHolder itemViewHolder = (ItemTouchHelperViewHolder) viewHolder;
-                itemViewHolder.onItemSelected();
-            }
+        if (actionState != ItemTouchHelper.ACTION_STATE_IDLE && viewHolder instanceof ItemTouchHelperViewHolder) {
```
Comment (barni9606) [inline app/src/main/java/app/outlay/view/helper/itemtouch/SimpleItemTouchHelperCallback.java]: concat if statements
